--DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN 2500
SELECT ENAME , JOB , SAL
FROM EMP 
WHERE SAL>2500;
--DISPLAY EMPLOYEES WHOSE DEPARTMENT NUMBER IS 10 OR 20
SELECT * 
FROM EMP
WHERE DEPTNO IN (10,20);
--DISPLAY EMPLOYEES NAMES WHOSE SALARY IS NOT BETWEEN 1000 AND 3000
SELECT ENAME, SAL
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;
--DISPLAY EMPLOYEES WHOSE JOB IS NOT CLERK
SELECT ENAME,JOB
FROM EMP
WHERE JOB NOT IN ('CLERK');
--DISPLAY EMPLOYEES NAMES ALONG WITH 10% BONUS AMOUNT
SELECT ENAME, SAL+SAL*10/100 SALARY_WITH_10HIKE
FROM EMP;
--DISPLAY EMPLOYEES WHOSE NAME CONTAINS 'A'
SELECT ENAME 
FROM EMP
WHERE ENAME LIKE '%A%';
--DISPLAY EMPLOYEE DETAILS SORTED BY DEPARTMENT NUMBER IN ASCENDING ORDER AND SALARY IN DESCENDING ORDER 
SELECT *
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;
--FIND THE TOTAL NUMBER OF EMPLOYEES IN EACH DEPARTMENT
SELECT  COUNT(*),DEPTNO
FROM EMP
GROUP BY DEPTNO;
--DISPLAY DEPATTMENTS WHERE TOTAL SALARY IS GREATER THAN 9000
SELECT DEPTNO, SUM(SAL) AS TOTAL_SALARY
FROM EMP
GROUP BY DEPTNO
HAVING SUM(SAL)>9000;
--DISPLAY AVERAGE SALARY OF EMPLOYEES IN EACH JOB
SELECT JOB,AVG(SAL)
FROM EMP 
GROUP BY JOB;
--DISPLAY EMPLOYEES WHOSE COMMISSION IS NOT NULL
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;
--FIND EMPLOYEES WHO WERE HIRED IN DECEMBER
SELECT * 
FROM EMP
WHERE TO_CHAR(HIREDATE,'MM')='12';
--DISPLAY EMPLOYEE NAMES AND YEARLY SALARY INCLUDING COMMISSION
SELECT ENAME, SAL,COMM, SAL*12 AS YEARLY_SALARY , SAL*12+COMM SAL_INCLUDE_COMM
FROM EMP;
--FIND EMPLOYEES WHOSE SALARY IS GREATER THAN ALL EMPLOYEES IN DEPARTMENT 30
SELECT ENAME, SAL
FROM EMP
WHERE SAL>ALL (SELECT SAL
FROM EMP 
WHERE DEPTNO IN (30));
--DISPLAY EMPLOYEES NAME, JOB AND SALARY WHOSE SALARY IS EVEN NUMBER
SELECT ENAME, JOB, SAL
FROM EMP
WHERE MOD(SAL,2)=0;
--FIND THE SECOND HIGHEST SALARY 
SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
	FROM EMP);
--DISPLAY EMPLOYEES WHOSE NAME IS 5 CHARACTERS LONG
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_____';
--FIND THE MANAGERS IDS AND HOW MANY EMPLOYEES WORK UNDER EACH MANAGER
SELECT MGR, COUNT(*)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;
--DISPLAY DEPARTMENT WISE MAXIMUM AND MINIMUM SALARY
SELECT MAX(SAL), MIN(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;
--FIND EMPLOYEES WHOSE SALARY IS LESS THAN THE AVERAGE SALARY OF THEIR DEPARTMENT
SELECT * 
FROM EMP
WHERE SAL<ALL (SELECT AVG (SAL) 
FROM EMP
GROUP BY DEPTNO);
--DISPLAY EMPLAYEES NAME AND HIREDATE IN 'DD-MON-YYYY' FORMAT
SELECT ENAME, TO_CHAR(HIREDATE,'DD-MON-YYYY') AS HIREDATE
FROM EMP;
--FIND EMPLOYEES WHOSE JOB STARTS WITH 'S'
SELECT  *
FROM EMP
WHERE JOB LIKE 'S%';
--DISPLAY JOB-WISE AVERAGE SALARY ORDERED FROM HIGHTEST TO LOWEST
SELECT  AVG(SAL), JOB
FROM EMP
GROUP BY JOB
ORDER BY AVG(SAL) DESC;
--FIND EMPLOYEES HIRED BEFORE 1982 AND SALARY GREATER THAN 1500
SELECT *
FROM EMP
WHERE HIREDATE < '01-JAN-1982' AND SAL > 1500;
--FIND EMPLOYEE NAME ALONG WITH SALARY AFTER ADDING 20% INCREMENT
SELECT ENAME, SAL, SAL+SAL*20/100 AS SAL_20PER_INCREMENT
FROM EMP;
--DISPLAY DEPARTMENTS HAVING MORE THAN 2 DIFFERENT JOB ROLES
SELECT COUNT(JOB), DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(JOB)>=2;
--DISPLAY EMPLOYEES WHOSE NAME ENDS WITH 'D'
SELECT * 
FROM EMP
WHERE ENAME LIKE '%D';
--FIND EMPLOYEES WHO DO NOT REPORT TO ANY MANAGER
SELECT *
FROM EMP
WHERE MGR IS NULL;
--DISPLAY THE TOTAL COMMISSION PAID DEPARTMENT WISE
SELECT SUM(COMM), DEPTNO
FROM EMP
GROUP BY DEPTNO;
--FIND EMPLOYEES EARNING THE SAME SALARY AS SCOTT
SELECT ENAME, SAL
FROM EMP
WHERE SAL=(SELECT SAL
FROM EMP
WHERE ENAME='SCOTT') AND ENAME NOT IN ('SCOTT');
