select * from EMP;

select * from DEPT;

select user from dual;

select user,sys_context('USERENV', 'current_schema')
from dual;

select owner, table_name from all_tables where table_name='emp';



--WAQTD DISTINCT JOB AND SALARY GIVEN TO THE EMPLOYEES
SELECT DISTINCT JOB, SAL
FROM EMP;

--WAQTD NAME AND ANNUAL SALARY WITH THE HIKE OF 10%
SELECT ENAME, SAL, SAL*12+SAL*12*10/5 AS "10_PERCENT_HIKE"
FROM EMP;

--WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH DEPTNO
SELECT EMP.*, DEPTNO
FROM EMP;

--WAQTD NAME, JOB,SALARY WITH A HIKE OF 20%
SELECT ENAME, JOB, SAL+SAL*20/100 AS "20_PERCENT_HIKE"
FROM EMP;

--WAQTD NAME, SAL AND SAL WITH DEDUCTION OF 35%
SELECT ENAME, SAL, SAL-SAL*35/100 AS "35_PERCENT_DEDUCTION"
FROM EMP;

--WAQTD DISTINCT NAME AND JOB , HIREDATE GIVEN TO THE EMPLOYEES
SELECT DISTINCT ENAME, JOB, HIREDATE
FROM EMP;

--WAQTD NAME AND SAL WTIH THE HIKE OF 500
SELECT ENAME, SAL+500 AS "SALARY_WITH_500_HIKE"
FROM EMP;

--WAQTD ALL THE DETAILS OF EMPLOYEES ALONG WITH EMPNO
SELECT EMP.*, EMPNO
FROM EMP;

--WAQTD DISTINCT NAME AND SALARY OF AN EMPLOYEE WITH A HIKE OF 3000
SELECT DISTINCT ENAME, SAL+3000 AS "SALARY_WITH_3000_HIKE"
FROM EMP;

--WAQTD NAME AND DESIGNATION ALONG WITH 1000 IN SALARY
