SELECT ENAME , JOB , SAL
FROM EMP 
WHERE SAL>2500;

SELECT * 
FROM EMP
WHERE DEPTNO IN (10,20);

SELECT ENAME, SAL
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;

SELECT ENAME,JOB
FROM EMP
WHERE JOB NOT IN ('CLERK');

SELECT ENAME, SAL+SAL*10/100 SALARY_WITH_10HIKE
FROM EMP;

SELECT ENAME 
FROM EMP
WHERE ENAME LIKE '%A%';

SELECT *
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

SELECT  COUNT(*),DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, SUM(SAL) AS TOTAL_SALARY
FROM EMP
GROUP BY DEPTNO
HAVING SUM(SAL)>9000;

SELECT JOB,AVG(SAL)
FROM EMP 
GROUP BY JOB;

SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

SELECT * 
FROM EMP
WHERE TO_CHAR(HIREDATE,'MM')='12';

SELECT ENAME, SAL
FROM EMP
WHERE SAL>ALL (SELECT SAL
FROM EMP 
WHERE DEPTNO IN (30));

SELECT ENAME, JOB, SAL
FROM EMP
WHERE MOD(SAL,2)=0;

SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
	FROM EMP);

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_____';

SELECT MGR, COUNT(*)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

SELECT MAX(SAL), MIN(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT * 
FROM EMP
WHERE SAL<ALL (SELECT AVG (SAL) 
FROM EMP
GROUP BY DEPTNO);

SELECT ENAME, TO_CHAR(HIREDATE,'DD-MON-YYYY') AS HIREDATE
FROM EMP;

SELECT  *
FROM EMP
WHERE JOB LIKE 'S%';

SELECT  AVG(SAL), JOB
FROM EMP
GROUP BY JOB
ORDER BY AVG(SAL) DESC;

SELECT *
FROM EMP
WHERE HIREDATE < '01-JAN-1982' AND SAL > 1500;

SELECT ENAME, SAL, SAL+SAL*20/100 AS SAL_20PER_INCREMENT
FROM EMP;
